import test from 'node:test';
import assert from 'node:assert/strict';
import {authoritativeConversationalTurns,authoritativeTurnEndpoint,compareAuthoritativeFreshness,FRONTEND_MESSAGE_TOOL,isExternalUserPrompt} from '../src/runtimes/rsc/authoritative-turns.mjs';
import {selectCarryover} from '../src/runtimes/rsc/selector.mjs';

const sid='11111111-1111-4111-8111-111111111111';let tick=0;
const rec=(type,content,extra={})=>({parentUuid:null,isSidechain:false,userType:'external',sessionId:sid,type,message:{role:type,content},uuid:crypto.randomUUID(),timestamp:new Date(Date.UTC(2026,0,1,0,0,tick++)).toISOString(),...extra});
const sys=subtype=>{const r=rec('system',[]);delete r.message;return {...r,subtype}};
const link=records=>records.map((r,i)=>({...r,parentUuid:i?records[i-1].uuid:null}));
const prompt=text=>' '+text?rec('user',[{type:'text',text}]):null;
const text=text=>rec('assistant',[{type:'text',text}]);
const tool=(name,input,id=crypto.randomUUID())=>rec('assistant',[{type:'tool_use',id,name,input}]);
const result=id=>rec('user',[{type:'tool_result',tool_use_id:id,content:'ignored-result'}]);
const terminal=()=>[sys('stop_hook_summary'),sys('turn_duration')];
const ordinary=(u='user-A',a='assistant-A')=>link([prompt(u),text(a),...terminal()]);
const frontend=(u='user-A',messages=['assistant-A'],ack='ack')=>{const records=[prompt(u)];for(const value of messages){const id=crypto.randomUUID();records.push(tool(FRONTEND_MESSAGE_TOOL,{text:value},id),result(id))}records.push({...text(ack),attributionMcpServer:'qiuqiu-frontend',attributionMcpTool:'send_frontend_message'},...terminal());return link(records)};
const turns=records=>authoritativeConversationalTurns(records);

test('01 external prompt starts turn',()=>assert.equal(isExternalUserPrompt(prompt('user-A')),true));
test('02 ordinary assistant terminal completes',()=>assert.equal(turns(ordinary()).turns.length,1));
test('03 tool result remains in same turn',()=>assert.equal(turns(frontend()).turns.length,1));
test('04 tool result does not start a turn',()=>assert.equal(isExternalUserPrompt(result('x')),false));
test('05 tool result does not terminate assistant search',()=>assert.equal(turns(frontend()).turns[0].complete,true));
test('06 next external prompt starts next turn',()=>{const all=link([...ordinary(),...ordinary('user-B','assistant-B')]);assert.equal(turns(all).turns.length,2)});
test('07 frontend text is extracted',()=>assert.equal(turns(frontend()).turns[0].assistantText,'assistant-A'));
test('08 arbitrary MCP input text is not extracted',()=>{const id='x';const all=link([prompt('user-A'),tool('mcp__other__tool',{text:'forbidden'},id),result(id),...terminal()]);assert.equal(turns(all).turns.length,0)});
test('09 tool result text is not extracted',()=>assert.doesNotMatch(turns(frontend()).turns[0].assistantText,/ignored-result/));
test('10 malformed frontend payload is rejected',()=>{const id='x';const all=link([prompt('user-A'),tool(FRONTEND_MESSAGE_TOOL,{text:'ok',extra:true},id),result(id),...terminal()]);assert.equal(turns(all).excluded[0].exclusionReason,'INVALID_FRONTEND_MESSAGE_PAYLOAD')});
test('11 missing frontend text is rejected',()=>{const id='x';const all=link([prompt('user-A'),tool(FRONTEND_MESSAGE_TOOL,{},id),result(id),...terminal()]);assert.equal(turns(all).turns.length,0)});
test('12 attributed acknowledgement is not duplicated',()=>assert.equal(turns(frontend()).turns[0].assistantMessages.length,1));
test('13 ordinary assistant text is canonical',()=>assert.equal(turns(ordinary()).turns[0].assistantText,'assistant-A'));
test('14 multiple frontend sends preserve order',()=>assert.deepEqual(turns(frontend('u',['bubble-A','bubble-B'])).turns[0].assistantMessages.map(x=>x.text),['bubble-A','bubble-B']));
test('15 multi-bubble count is preserved',()=>assert.equal(turns(frontend('u',['a','b','c'])).turns[0].assistantMessages.length,3));
test('16 StopFailure excludes completion',()=>{const r=ordinary();r.splice(-2,0,sys('stop_failure'));assert.equal(turns(link(r)).turns.length,0)});
test('17 missing terminal excludes turn',()=>assert.equal(turns(link([prompt('u'),text('a')])).turns.length,0));
test('18 missing tool result excludes incomplete tool turn',()=>{const all=link([prompt('u'),tool(FRONTEND_MESSAGE_TOOL,{text:'a'},'x'),...terminal()]);assert.equal(turns(all).excluded[0].exclusionReason,'MISSING_TOOL_RESULT')});
test('19 orphan parent excludes turn',()=>{const all=ordinary();all[1].parentUuid='missing';assert.equal(turns(all).turns.length,0)});
test('20 side branch is excluded',()=>{const main=ordinary(),side={...prompt('side'),isSidechain:true,parentUuid:main[0].uuid};assert.equal(turns([...main,side]).turns.length,1)});
test('21 active branch is included',()=>assert.equal(turns(ordinary()).turns[0].activeBranch,true));
test('22 timestamp regression keeps physical branch order',()=>{const all=ordinary();all[1].timestamp='2025-01-01T00:00:00.000Z';assert.equal(turns(all).turns.length,1)});
test('23 startup metadata is ignored',()=>{const all=ordinary();all.splice(1,0,{type:'mode',mode:'x',sessionId:sid});assert.equal(turns(all).turns.length,1)});
test('24 resume metadata is ignored',()=>{const all=ordinary();all.push({type:'permission-mode',permissionMode:'x',sessionId:sid});assert.equal(turns(all).turns.length,1)});
test('25 compact artifact is not payload',()=>{const all=ordinary();all.splice(1,0,{type:'summary',summary:'bad',isCompactSummary:true,sessionId:sid});assert.equal(turns(all).turns[0].assistantText,'assistant-A')});
test('26 freshness endpoint equals selector endpoint',()=>{const all=ordinary();assert.equal(authoritativeTurnEndpoint(all).identity.turnId,selectCarryover(all).selected.at(-1).id)});
test('27 byte-only metadata change is not conversationally stale',()=>{const a=ordinary(),b=[...a,{type:'mode',mode:'x',sessionId:sid}];assert.equal(compareAuthoritativeFreshness(a,b).conversationallyStale,false)});
test('28 new completed turn is stale',()=>{const a=ordinary(),b=link([...a,...ordinary('u2','a2')]);assert.equal(compareAuthoritativeFreshness(a,b).conversationallyStale,true)});
test('29 partial turn does not advance endpoint',()=>{const a=ordinary(),b=link([...a,prompt('partial')]);assert.equal(compareAuthoritativeFreshness(a,b).conversationallyStale,false)});
test('30 tool-only turn without payload is excluded',()=>{const id='x',all=link([prompt('u'),tool('mcp__other__tool',{},id),result(id),...terminal()]);assert.equal(turns(all).turns.length,0)});
test('31 tool JSON does not leak',()=>{const r=turns(frontend()).turns[0];assert.doesNotMatch(r.assistantText,/tool_use|input|tool_result/)});
test('32 secret path and base64 fields do not leak',()=>{const r=turns(frontend()).turns[0];assert.doesNotMatch(r.assistantText,/\/root\/|Bearer|base64/)});
test('33 duplicate assistant payload is prevented',()=>assert.equal(turns(frontend('u',['same'],'same')).turns[0].assistantText,'same'));
test('34 frontend allowlist is exact',()=>{const id='x',all=link([prompt('u'),tool(FRONTEND_MESSAGE_TOOL+'x',{text:'bad'},id),result(id),...terminal()]);assert.equal(turns(all).turns.length,0)});
test('35 production-shaped 33 turns are all recognized',()=>{const all=[];for(let i=0;i<33;i++)all.push(...frontend('user-'+i,['assistant-'+i]));assert.equal(turns(link(all)).turns.length,33)});
