import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {durableReadyEvidence,classifyStartupScreen} from '../deploy/rsc-startup-trust.mjs';import {targetReadyEvidence} from '../deploy/rsc-activation-safety.mjs';import {createProductionRscStateStore,createProductionRscCoordinator,shouldQueueRscSend} from '../src/runtimes/rsc/production-state.mjs';
const source='11111111-1111-4111-8111-111111111111',target='22222222-2222-4222-8222-222222222222';
const state=(handoffState='CANDIDATE_ACTIVE')=>({currentProductionSessionId:source,lastGoodSessionId:source,preparedTargetSessionId:target,preparedTargetEvidence:'PREPARED',handoffState,handoffGeneration:1,operationGeneration:1,operationId:'operation_12345678',updatedAt:new Date().toISOString()});
const ready=(over={})=>({claudeAlive:true,resumedSessionId:target,workspaceRoot:true,tmuxIdentity:true,singleManagedClaude:true,runtimeConnected:true,active:false,activeTurnId:null,helperAlive:true,helperParentMatches:true,oldHelperAbsent:true,helperIdentityMatches:true,frontendMcpConnected:true,obConfigured:true,modelExact:true,effortHigh:true,noModelFallback:true,transcriptParseable:true,permissionsIntact:true,hooksIntact:true,claudeMdAvailable:true,onboardingDetected:false,startupError:false,autoCompacted:false,emptySessionFallback:false,...over});
async function fixture(value=state()){const dir=await mkdtemp(join(tmpdir(),'candidate-')),store=createProductionRscStateStore({path:join(dir,'state.json')});await store.save(value);return{store,coordinator:createProductionRscCoordinator({stateStore:store})}}
test('01 candidate startup without metadata flush passes',()=>assert.equal(durableReadyEvidence({parseable:true,transcriptWritable:true,startupStructureValid:true}),true));
test('02 OAuth gate fails classification',()=>assert.equal(classifyStartupScreen('OAuth sign in required').kind,'OAUTH'));
test('03 permission gate fails classification',()=>assert.equal(classifyStartupScreen('permission request required').kind,'PERMISSION'));
test('04 wrong session fails target readiness',()=>assert.equal(targetReadyEvidence(ready({resumedSessionId:source}),target),false));
test('05 real third Claude fails ownership readiness',()=>assert.equal(targetReadyEvidence(ready({singleManagedClaude:false}),target),false));
test('06 candidate run failure does not commit or repost',async()=>{const f=await fixture(),calls=[];await assert.rejects(f.coordinator.submit({clientRequestId:'req'},async()=>{calls.push('once');throw Error('failed')}));assert.deepEqual(calls,['once']);assert.equal((await f.store.load()).handoffState,'CANDIDATE_ACTIVE')});
test('07 first real turn success commits',async()=>{const f=await fixture();await f.coordinator.submit({clientRequestId:'req'},async()=>7);const s=await f.store.load();assert.equal(s.handoffState,'ACTIVE');assert.equal(s.currentProductionSessionId,target);assert.equal(s.lastGoodSessionId,target)});
test('08 queued request releases exactly once',async()=>{const f=await fixture(state('ACTIVATING')),seen=[];const p=f.coordinator.submit({clientRequestId:'req'},async()=>seen.push('run'));await f.store.save(state('CANDIDATE_ACTIVE'));await f.coordinator.releaseToAuthoritative();await p;assert.deepEqual(seen,['run'])});
test('09 accepted request failure is not reposted',async()=>{const f=await fixture(),seen=[];await assert.rejects(f.coordinator.submit({clientRequestId:'req'},async()=>{seen.push('accepted');throw Error('after accept')}));assert.equal(seen.length,1)});
test('10 NOT_FOUND remains safe candidate state',async()=>{const f=await fixture();await assert.rejects(f.coordinator.submit({clientRequestId:'req'},async()=>{throw Object.assign(Error('NOT_FOUND'),{status:'NOT_FOUND'})}));assert.equal((await f.store.load()).handoffState,'CANDIDATE_ACTIVE')});
test('11 candidate state leaves gate open',()=>assert.equal(shouldQueueRscSend(state()),false));
test('12 frontend conversation identity is absent from state',()=>{for(const key of ['conversationId','messages','draft','history'])assert.equal(key in state(),false)});
