import test from 'node:test';import assert from 'node:assert/strict';import {resolveOwnershipCandidates} from '../scripts/rsc-shadow-ownership-forensics.mjs';
const prod=10,shadow=20,base={pid:30,comm:'claude',exe:'/usr/bin/claude',argv:['rg','--files','/root'],status:{Name:'claude',PPid:'20'},stat:{starttime:'1',session:'20',pgrp:'20'},cgroup:'scope',parentChain:[{pid:20,stat:{session:'20',pgrp:'20'},cgroup:'scope'}]};
const run={...base,argv:['/usr/bin/claude','--resume','x']};const resolve=(value=base,o={})=>resolveOwnershipCandidates({owners:[prod,shadow,30],expectedProductionPid:prod,expectedShadowPid:shadow,sample:async()=>structuredClone(value),delay:async()=>{},...o});
test('01 production plus shadow pass',async()=>assert((await resolveOwnershipCandidates({owners:[prod,shadow],expectedProductionPid:prod,expectedShadowPid:shadow})).valid));
test('02 genuine third Claude fails',async()=>assert(!(await resolve(run)).valid));
test('03 unrelated Claude fails',async()=>assert(!(await resolve({...run,status:{Name:'claude',PPid:'1'}})).valid));
test('04 direct transient child not owner',async()=>assert((await resolve()).valid));
test('05 exe initially claude then child not owner',async()=>assert((await resolve()).valid));
test('06 comm initially claude then utility not owner',async()=>assert((await resolve({...base,comm:'rg'})).valid));
test('07 child stable runtime fails',async()=>assert(!(await resolve(run)).valid));
test('08 same cgroup independent fails',async()=>assert(!(await resolve({...base,status:{Name:'claude',PPid:'1'}})).valid));
test('09 same pgrp alone insufficient',async()=>assert(!(await resolve({...base,status:{Name:'claude',PPid:'1'},cgroup:'other'})).valid));
test('10 same PPID alone insufficient',async()=>assert(!(await resolve({...base,stat:{...base.stat,session:'9'}})).valid));
test('11 PID reuse fails',async()=>{let n=0;assert(!(await resolve(base,{sample:async()=>({...structuredClone(base),stat:{...base.stat,starttime:String(++n)}})})).valid)});
test('12 exit during stabilization safe',async()=>{let n=0;const x=await resolve(base,{sample:async()=>++n===1?base:{...base,status:{unavailable:'PROCESS_EXITED_DURING_CAPTURE'}}});assert(x.valid)});
test('13 inconsistent snapshots bounded fail',async()=>{let n=0;assert(!(await resolve(base,{sample:async()=>({...base,stat:{...base.stat,starttime:String(++n)}})})).valid)});
test('14 stabilization honors deadline',async()=>assert.rejects(resolve(base,{deadlineAt:24,now:()=>0,delayMs:25}),/FAILED_STARTUP_TIMEOUT/));
test('15 diagnostics retained',async()=>assert.equal((await resolve()).diagnostics.length,1));
test('16 sanitized capture reused',async()=>assert.equal((await resolve()).diagnostics[0].second.environment,undefined));
test('17 no PID whitelist',async()=>assert(!(await resolve({...run,pid:400440})).valid));
test('18 no utility-name exemption',async()=>assert((await resolve({...base,argv:['anything']})).valid));
test('19 no arbitrary PID API',()=>assert.equal('browserPid' in base,false));
test('20 detector does not spawn',async()=>assert((await resolve()).valid));
test('21 production unique',async()=>assert((await resolveOwnershipCandidates({owners:[prod,shadow],expectedProductionPid:prod,expectedShadowPid:shadow})).valid));
test('22 shadow unique',async()=>assert((await resolveOwnershipCandidates({owners:[prod,shadow],expectedProductionPid:prod,expectedShadowPid:shadow})).valid));
test('23 helper node not discovered',async()=>assert((await resolveOwnershipCandidates({owners:[prod,shadow],expectedProductionPid:prod,expectedShadowPid:shadow})).valid));
test('24 real child utility classified managed',async()=>assert.equal((await resolve()).managedChildren[0].classification,'MANAGED_CLAUDE_CHILD'));
