import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,stat} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {captureProcess,captureAndRejectOwnership,atomicWriteForensics} from '../scripts/rsc-shadow-ownership-forensics.mjs';
const status='Name:\tclaude\nState:\tS\nPPid:\t20\nUid:\t0\t0\t0\t0\nGid:\t0\t0\t0\t0\nNSpid:\t30\n',statLine='30 (claude) S 20 10 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 777 0',files={'/proc/30/status':status,'/proc/30/stat':statLine,'/proc/30/cmdline':'/usr/bin/claude\0--version\0','/proc/30/environ':'HOME=/root\0USER=root\0LOGNAME=root\0TOKEN=nope\0','/proc/30/cgroup':'0::/scope\n','/proc/30/sessionid':'10\n','/proc/20/status':status.replace('PPid:\t20','PPid:\t1').replace('Name:\tclaude','Name:\tsh'),'/proc/20/stat':statLine,'/proc/20/cmdline':'/bin/sh\0','/proc/20/environ':'HOME=/root\0','/proc/20/cgroup':'0::/scope\n','/proc/20/sessionid':'10\n','/proc/1/status':status.replace('PPid:\t20','PPid:\t0').replace('Name:\tclaude','Name:\tinit'),'/proc/1/stat':statLine,'/proc/1/cmdline':'/sbin/init\0','/proc/1/environ':'HOME=/\0','/proc/1/cgroup':'0::/init\n','/proc/1/sessionid':'1\n'};
const read=async p=>{if(!(p in files))throw Object.assign(Error('gone'),{code:'ENOENT'});return Buffer.from(files[p])},link=async p=>p.endsWith('/exe')?'/usr/bin/claude':p.endsWith('/cwd')?'/root':Promise.reject(Object.assign(Error('gone'),{code:'ENOENT'}));
const capture=()=>captureProcess(30,{readFileFn:read,readlinkFn:link});
test('01 unexpected captured before throw',async()=>{let wrote=false;await assert.rejects(captureAndRejectOwnership({owners:[1,2,30],expectedProductionPid:1,expectedShadowPid:2,path:'x',captureProcessFn:capture,writeFn:async()=>{wrote=true}}));assert(wrote)});
for(const [n,key,value] of [[2,'exe','/usr/bin/claude'],[3,'argv','/usr/bin/claude'],[4,'status','20'],[5,'status','0'],[6,'cwd','/root'],[7,'stat','777'],[8,'cgroup','/scope']])test(`${String(n).padStart(2,'0')} captures ${key}`,async()=>assert(JSON.stringify((await capture())[key]).includes(value)));
test('09 captures parent chain',async()=>assert.equal((await capture()).parentChain[0].pid,20));
test('10 exited process is recorded',async()=>assert.equal((await captureProcess(99,{readFileFn:read,readlinkFn:link})).captureCompleteness,'PARTIAL'));
test('11 partial evidence retained',async()=>assert.equal((await captureProcess(99,{readFileFn:read,readlinkFn:link})).pid,99));
test('12 persistence precedes rejection',async()=>{const order=[];await assert.rejects(captureAndRejectOwnership({owners:[1,2,30],expectedProductionPid:1,expectedShadowPid:2,path:'x',captureProcessFn:capture,writeFn:async()=>order.push('write')}));order.push('throw');assert.deepEqual(order,['write','throw'])});
test('13 secrets excluded',async()=>assert(!JSON.stringify(await capture()).includes('nope')));
test('14 OAuth excluded',async()=>assert(!JSON.stringify(await capture()).toLowerCase().includes('oauth=')));
test('15 API key excluded',async()=>assert(!JSON.stringify(await capture()).toLowerCase().includes('api_key=')));
test('16 Bearer excluded',async()=>assert(!JSON.stringify(await capture()).includes('Bearer ')));
test('17 validator still rejects',async()=>assert.rejects(captureAndRejectOwnership({owners:[1,2,30],expectedProductionPid:1,expectedShadowPid:2,path:'x',captureProcessFn:capture,writeFn:async()=>{}}),/FAILED_OWNERSHIP_MISMATCH/));
test('18 normal pair passes',async()=>assert.equal((await captureAndRejectOwnership({owners:[1,2],expectedProductionPid:1,expectedShadowPid:2})).valid,true));
test('19 instrumentation does not spawn Claude',()=>assert.doesNotMatch(captureProcess.toString(),/spawn|execFile/));
test('20 owner count unchanged',async()=>{const owners=[1,2];await captureAndRejectOwnership({owners,expectedProductionPid:1,expectedShadowPid:2});assert.deepEqual(owners,[1,2])});
test('21 no input sender exists',()=>assert.doesNotMatch(captureAndRejectOwnership.toString(),/send-keys|stdin/));
test('22 conversation body absent',async()=>assert(!JSON.stringify(await capture()).includes('message')));
test('23 evidence writer enforces 0600',()=>assert.match(atomicWriteForensics.toString(),/0o600/));
test('24 no browser PID/path API',()=>assert.doesNotMatch(captureAndRejectOwnership.toString(),/request|response|browser|http/));
