import test from 'node:test';import assert from 'node:assert/strict';
import {waitForPostTrustReady,handleManagedStartup,durableReadyEvidence,POST_TRUST_POLL_MS,POST_TRUST_DEADLINE_MS,READY_STABILIZATION_MS} from '../deploy/rsc-startup-trust.mjs';
import {shadowLaunchSpec} from '../src/runtimes/rsc/shadow.mjs';
const id='22222222-2222-4222-8222-222222222222',ready='Claude Code v2.1.236\n/root\n❯ Try "hello"',trust=`Accessing workspace:\n/root\nQuick safety check: Is this a project you created or one you trust?\nClaude Code'll be able to read, edit, and execute files here.\n❯ 1. Yes, I trust this folder\n2. No, exit`;
const durable={parseable:true,transcriptWritable:true,resumeHistoryInitialized:true,resumeMetadataInitialized:true,modeObserved:true,permissionModeObserved:true,resumeMilestone:true,startupStructureValid:true,wrongSessionRecord:false,orphanStartupRecord:false,user:0,assistant:0,compact:false};
const runtime={processAlive:true,exactSession:true,ownershipIntact:true,unexpectedClaudeOwner:false,unexpectedHelperOwner:false,uid:0,home:'/root',canonicalCwd:'/root'};
const ctx=(o={})=>({executable:'/usr/bin/claude',version:'2.1.236',managedOperation:true,targetSessionId:id,expectedTargetSessionId:id,uid:0,home:'/root',canonicalCwd:'/root',displayedWorkspace:'/root',unexpectedClaudeOwner:false,unexpectedHelperOwner:false,...o});
function sim({screens=[''],transcripts=durable,runtimes=runtime,deadline=2000,poll=250,initialTrust=false,readyValue=true}={}){let i=0,t=0,inputs=0,post=!initialTrust;const pick=(v)=>typeof v==='function'?v(i):Array.isArray(v)?v[Math.min(i,v.length-1)]:v;return {screen:async()=>post?pick(screens):trust,conversationCounts:async()=>({user:0,assistant:0}),permissionFingerprint:async()=>'p',confirmSelectedOption:async()=>{inputs++;post=true},runtimeEvidence:async()=>({...runtime,...pick(runtimes)}),transcriptEvidence:async()=>({...durable,...pick(transcripts)}),readyEvidence:async()=>readyValue,mcpCallCount:async()=>0,timing:{pollMs:poll,deadlineMs:deadline,now:()=>t,sleep:async ms=>{t+=ms;i++}},get time(){return t},get inputs(){return inputs}}}
const wait=c=>waitForPostTrustReady({controller:c,baseline:{user:0,assistant:0},...c.timing});
const fails=(c,reason)=>assert.rejects(wait(c),e=>e.reason===reason);
test('01 metadata plus blank stabilizes READY',async()=>assert.equal((await wait(sim())).state,'READY'));
test('02 noninteractive redraw stabilizes READY',async()=>assert.equal((await wait(sim({screens:['loading','painted history']}))).state,'READY'));
test('03 legacy main UI stabilizes READY',async()=>assert.equal((await wait(sim({screens:[ready]}))).state,'READY'));
test('04 UI without durable evidence is not READY',async()=>fails(sim({screens:[ready],transcripts:{resumeMilestone:false},deadline:750}),'FAILED_STARTUP_TIMEOUT'));
test('05 parseable unchanged transcript is sufficient positive transcript evidence',()=>assert.equal(durableReadyEvidence({parseable:true,transcriptWritable:true}),true));
test('06 exact session only is insufficient',async()=>fails(sim({transcripts:{resumeMilestone:false},deadline:500}),'FAILED_STARTUP_TIMEOUT'));
test('07 missing permission metadata does not block startup',()=>assert.equal(durableReadyEvidence({...durable,permissionModeObserved:false,resumeMilestone:false}),true));
test('08 missing mode metadata does not block startup',()=>assert.equal(durableReadyEvidence({...durable,modeObserved:false,resumeMilestone:false}),true));
test('09 safe extra metadata does not block',async()=>assert.equal((await wait(sim({transcripts:{metadata:['progress']}}))).state,'READY'));
test('10 timestamps are not required',()=>assert.equal(durableReadyEvidence(durable),true));
test('11 sessionless history snapshot can be associated',()=>assert.equal(durableReadyEvidence({...durable,historySessionId:null}),true));
test('12 wrong-session mode fails closed',async()=>fails(sim({transcripts:{wrongSessionRecord:true}}),'FAILED_TRANSCRIPT_SESSION'));
test('13 wrong-session permission mode fails closed',async()=>fails(sim({transcripts:{wrongSessionRecord:true}}),'FAILED_TRANSCRIPT_SESSION'));
test('14 user mutation fails closed',async()=>fails(sim({transcripts:{user:1}}),'UNEXPECTED_USER_RECORD'));
test('15 assistant mutation fails closed',async()=>fails(sim({transcripts:{assistant:1}}),'UNEXPECTED_ASSISTANT_RECORD'));
test('16 compact fails closed',async()=>fails(sim({transcripts:{compact:true}}),'UNEXPECTED_COMPACT'));
test('17 parse corruption fails closed',async()=>fails(sim({transcripts:{parseable:false}}),'FAILED_TRANSCRIPT_PARSE'));
test('18 orphan startup structure fails closed',async()=>fails(sim({transcripts:{orphanStartupRecord:true}}),'FAILED_TRANSCRIPT_STRUCTURE'));
for(const [n,label,screen] of [[19,'OAuth','OAuth authorization'],[20,'login','Log in to continue'],[21,'permission','Permission prompt required'],[22,'theme','Choose a theme'],[23,'resume','Continue session?']])test(`${n} milestone then ${label} fails`,async()=>fails(sim({screens:['',screen]}),'UNEXPECTED_POST_TRUST_GATE'));
test('24 stable interactive unknown fails',async()=>fails(sim({screens:['Mystery\n1. Continue\nEnter to select']}),'UNEXPECTED_POST_TRUST_GATE'));
test('25 transient unknown can stabilize',async()=>assert.equal((await wait(sim({screens:['partial paint','', '', '', '', '']}))).state,'READY'));
test('26 stable blank is allowed',async()=>assert.equal((await wait(sim({screens:['']}))).state,'READY'));
test('27 first durable poll is not immediate READY',async()=>{const c=sim();await wait(c);assert(c.time>=1000)});
test('28 stabilization is at least 1000ms',()=>assert.equal(READY_STABILIZATION_MS,1000));
test('29 poll remains 250ms',()=>assert.equal(POST_TRUST_POLL_MS,250));
test('30 deadline remains 30s',()=>assert.equal(POST_TRUST_DEADLINE_MS,30000));
test('31 process exit during stabilization fails',async()=>fails(sim({runtimes:i=>({processAlive:i<2})}),'FAILED_PROCESS_EXIT'));
test('32 session change during stabilization fails',async()=>fails(sim({runtimes:i=>({exactSession:i<2})}),'FAILED_SESSION_MISMATCH'));
test('33 ownership loss during stabilization fails',async()=>fails(sim({runtimes:i=>({ownershipIntact:i<2})}),'FAILED_OWNERSHIP_MISMATCH'));
test('34 unexpected Claude owner fails',async()=>fails(sim({runtimes:{unexpectedClaudeOwner:true}}),'FAILED_OWNERSHIP_MISMATCH'));
test('35 unexpected helper owner fails',async()=>fails(sim({runtimes:{unexpectedHelperOwner:true}}),'FAILED_OWNERSHIP_MISMATCH'));
test('36 trust Enter remains once',async()=>{const c=sim({initialTrust:true});await handleManagedStartup({context:ctx(),controller:c});assert.equal(c.inputs,1)});
test('37 confirmed/redraw does not duplicate input',async()=>{const c=sim({initialTrust:true,screens:['','',ready]});await handleManagedStartup({context:ctx(),controller:c});assert.equal(c.inputs,1)});
test('38 no-trust blank durable startup is READY',async()=>assert.equal((await handleManagedStartup({context:ctx(),controller:sim()})).state,'READY'));
test('39 exact root trust durable startup is READY',async()=>assert.equal((await handleManagedStartup({context:ctx(),controller:sim({initialTrust:true})})).state,'READY'));
test('40 wrong workspace trust fails closed',async()=>{const c=sim({initialTrust:true});c.screen=async()=>trust.replace('/root','/tmp');await assert.rejects(handleManagedStartup({context:ctx(),controller:c}),e=>e.reason==='MANAGED_TRUST_CONTEXT_REJECTED')});
test('41 OAuth before milestone fails closed',async()=>fails(sim({screens:['OAuth required'],transcripts:{resumeMilestone:false}}),'UNEXPECTED_POST_TRUST_GATE'));
test('42 OAuth after milestone fails closed',async()=>fails(sim({screens:['','OAuth required']}),'UNEXPECTED_POST_TRUST_GATE'));
test('43 screen READY is optional',async()=>assert.equal((await wait(sim({screens:['']}))).uiReadyEvidence,false));
test('44 screen READY cannot bypass durable evidence',async()=>fails(sim({screens:[ready],transcripts:{resumeMilestone:false},deadline:500}),'FAILED_STARTUP_TIMEOUT'));
test('45 strict empty MCP remains valid',()=>assert(shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'}).args.includes('--strict-mcp-config')));
test('46 no helper is required',async()=>assert.equal((await wait(sim())).state,'READY'));
test('47 no MCP connection is required',async()=>assert.equal((await wait(sim())).state,'READY'));
test('48 no runtime takeover is required',async()=>assert.equal((await wait(sim())).state,'READY'));
test('49 post READY final boundary callback executes',async()=>{let calls=0;const c=sim();c.readyEvidence=async()=>{calls++;return true};await wait(c);assert(calls>=5)});
test('50 Phase2-equivalent metadata reaches READY',async()=>assert.equal((await wait(sim())).state,'READY'));
test('51 V4-equivalent metadata plus blank reaches READY',async()=>assert.equal((await wait(sim({screens:['','','','','']}))).state,'READY'));
test('52 missing Try glyph cannot cause timeout',async()=>assert.equal((await wait(sim({screens:['existing conversation history']}))).state,'READY'));
