import test from 'node:test';import assert from 'node:assert/strict';
import {createRuntimeObservability} from '../src/runtimes/rsc/runtime-observability.mjs';
const base={runtimeActive:false,activeTurnId:null,unfinishedJournalCount:0,finalizationInProgress:false};
const fixture=(over={})=>{let gate={state:'OPEN',queueDepth:0,oldestQueuedMs:null,generation:1,handoffGeneration:1,handoffState:'VALIDATED'};const runtime={quiescence:()=>({...base,...over.runtime})},images={quiescence:()=>({transitionalImageBindingCount:0,...over.image})},coordinator={snapshot:async()=>({...gate,...over.gate})};return createRuntimeObservability({runtime,imageStore:images,coordinator})};
test('idle production is quiescent only after reconciliation',async()=>{const o=fixture();assert.equal((await o.snapshot()).quiescent,false);const s=await o.reconcile();assert.equal(s.quiescent,true);assert.deepEqual(s.blockers,[])});
test('unknown state never becomes quiescent',async()=>{for(const over of [{runtime:{unfinishedJournalCount:undefined}},{image:{transitionalImageBindingCount:undefined}},{gate:{generation:undefined}}]){const o=fixture(over);await o.reconcile();assert.equal((await o.snapshot()).quiescent,false)}});
test('runtime, journal, finalization, image and gate blockers are explicit',async()=>{for(const over of [{runtime:{runtimeActive:true}},{runtime:{activeTurnId:'turn'}},{runtime:{unfinishedJournalCount:1}},{runtime:{finalizationInProgress:true}},{image:{transitionalImageBindingCount:1}},{gate:{state:'CLOSED'}},{gate:{queueDepth:1}}]){const o=fixture(over);await o.reconcile();assert.equal((await o.snapshot()).quiescent,false)}});
test('recovery counter releases in finally',async()=>{const o=fixture();await o.reconcile();await assert.rejects(o.recovery(async()=>{assert.equal((await o.snapshot()).recoveryInProgress,true);throw Error('x')}));assert.equal((await o.snapshot()).recoveryCount,0)});
test('post-freeze accepts a closed gate and queue but rejects active runtime',async()=>{const o=fixture({gate:{state:'CLOSED',queueDepth:1}});await o.reconcile();assert.equal((await o.snapshot({frozen:true})).quiescent,true);const blocked=fixture({gate:{state:'CLOSED'},runtime:{runtimeActive:true}});await blocked.reconcile();assert.equal((await blocked.snapshot({frozen:true})).quiescent,false)});
const cases=[
 ['1 idle production',{},false,true],['2 runtime active',{runtime:{runtimeActive:true}},false,false],['3 active turn',{runtime:{activeTurnId:'t'}},false,false],['4 unfinished journal',{runtime:{unfinishedJournalCount:1}},false,false],['5 finalization',{runtime:{finalizationInProgress:true}},false,false],['7 image transition',{image:{transitionalImageBindingCount:1}},false,false],['8 gate closed',{gate:{state:'CLOSED'}},false,false],['9 queue occupied',{gate:{queueDepth:1}},false,false],['10 generation mismatch',{gate:{generation:2}},false,false],['11 unknown journal',{runtime:{unfinishedJournalCount:undefined}},false,false],['13 unknown image',{image:{transitionalImageBindingCount:undefined}},false,false],['15 finished journal absent',{},false,true],['16 completed recovery absent',{},false,true],['17 stable temp image',{},false,true],['23 pre activation needs open', {gate:{state:'CLOSED'}},false,false],['24 frozen closed empty',{gate:{state:'CLOSED'}},true,true],['25 frozen closed queued',{gate:{state:'CLOSED',queueDepth:1}},true,true],['26 frozen runtime active',{runtime:{runtimeActive:true}},true,false],['27 frozen finalization',{runtime:{finalizationInProgress:true}},true,false],['29 frozen image',{image:{transitionalImageBindingCount:1}},true,false],['30 before reconcile',{},false,false],['31 after reconcile',{},false,true],['35 deterministic production shape',{},false,true]
];
for(const [name,over,frozen,expected] of cases)test(name,async()=>{const o=fixture(over);if(name!=='30 before reconcile')await o.reconcile();const a=await o.snapshot({frozen}),b=await o.snapshot({frozen});assert.equal(a.quiescent,expected);assert.deepEqual(a.blockers,b.blockers)});
test('6 recovery job blocks',async()=>{const o=fixture();await o.reconcile();const p=o.recovery(async()=>{assert.equal((await o.snapshot()).quiescent,false)});await p});
test('12 unknown recovery is blocked by active counter',async()=>{const o=fixture();await o.reconcile();await o.recovery(async()=>assert.equal((await o.snapshot()).recoveryCount,1))});
test('14 observability not ready blocks',async()=>assert.equal((await fixture().snapshot()).blockers.includes('OBSERVABILITY_NOT_READY'),true));
test('18 finalization releases',async()=>{const o=fixture();await o.reconcile();assert.equal((await o.snapshot()).finalizationInProgress,false)});
test('19 recovery releases',async()=>{const o=fixture();await o.reconcile();await o.recovery(async()=>{});assert.equal((await o.snapshot()).recoveryCount,0)});
test('20 image transition known zero releases',async()=>{const o=fixture();await o.reconcile();assert.equal((await o.snapshot()).transitionalImageBindingCount,0)});
test('21 same coordinator snapshot',async()=>{const o=fixture();await o.reconcile();assert.equal((await o.snapshot()).sendGateGeneration,1)});
test('22 gate snapshot hides request content',async()=>{const o=fixture();await o.reconcile();assert.equal(JSON.stringify(await o.snapshot()).includes('prompt'),false)});
test('28 frozen recovery rejects',async()=>{const o=fixture();await o.reconcile();await o.recovery(async()=>assert.equal((await o.snapshot({frozen:true})).quiescent,false))});
test('32 unified snapshot is consumable',async()=>{const o=fixture();await o.reconcile();assert.equal((await o.snapshot()).quiescent,true)});
test('33 blocked snapshot does not invoke lifecycle',async()=>{let stopped=false;const o=fixture({runtime:{runtimeActive:true}});await o.reconcile();assert.equal((await o.snapshot()).quiescent,false);assert.equal(stopped,false)});
test('34 no public observability endpoint is created',async()=>{const {createDwellServer}=await import('../server.mjs');const s=createDwellServer({});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{assert.equal((await fetch(`http://127.0.0.1:${s.address().port}/api/rsc/status`)).status,404)}finally{s.close()}});
