import test from 'node:test';import assert from 'node:assert/strict';
import {acceptWorkspaceTrustGate,classifyStartupScreen,handleManagedStartup,POST_TRUST_DEADLINE_MS,POST_TRUST_POLL_MS,validateManagedTrustContext,waitForPostTrustReady} from '../deploy/rsc-startup-trust.mjs';import {shadowLaunchSpec} from '../src/runtimes/rsc/shadow.mjs';
const id='22222222-2222-4222-8222-222222222222',trust=`Accessing workspace:\n\n/root\n\nQuick safety check: Is this a project you created or one you trust?\nClaude Code'll be able to read, edit, and execute files here.\n❯ 1. Yes, I trust this folder\n2. No, exit`,confirmed=trust.replace('folder','folder ✔'),ready='Claude Code v2.1.236\nSonnet 4.6 · /root\n❯ Try "hello"',ctx=(o={})=>({executable:'/usr/bin/claude',version:'2.1.236',managedOperation:true,targetSessionId:id,expectedTargetSessionId:id,uid:0,home:'/root',canonicalCwd:'/root',displayedWorkspace:'/root',unexpectedClaudeOwner:false,unexpectedHelperOwner:false,...o});
function sim(frames,{runtime={},transcript={},deadline=30000,poll=250}={}){
 let i=0,t=0,inputs=0,post=false;const frame=()=>post?frames[Math.min(i,frames.length-1)]:trust;
 return {screen:async()=>frame(),conversationCounts:async()=>({user:0,assistant:0}),permissionFingerprint:async()=>'p',confirmSelectedOption:async()=>{inputs++;post=true},runtimeEvidence:async()=>Object.assign({processAlive:true,exactSession:true,ownershipIntact:true,unexpectedClaudeOwner:false,unexpectedHelperOwner:false,uid:0,home:'/root',canonicalCwd:'/root'},typeof runtime==='function'?runtime(i):runtime),transcriptEvidence:async()=>Object.assign({parseable:true,transcriptWritable:true,resumeHistoryInitialized:true,resumeMetadataInitialized:true,modeObserved:true,permissionModeObserved:true,resumeMilestone:true,startupStructureValid:true,wrongSessionRecord:false,orphanStartupRecord:false,user:0,assistant:0,compact:false},typeof transcript==='function'?transcript(i):transcript),readyEvidence:async()=>true,mcpCallCount:async()=>0,timing:{pollMs:poll,deadlineMs:deadline,now:()=>t,sleep:async ms=>{t+=ms;i++}},get inputs(){return inputs}};
}
const accept=c=>acceptWorkspaceTrustGate({context:ctx(),controller:c}),reject=(p,r)=>assert.rejects(p,e=>e.reason===r);
test('01 no trust direct READY',async()=>assert.equal((await handleManagedStartup({context:ctx(),controller:sim([ready],{runtime:{}})})).state,'READY'));
for(const [n,name,frames] of [[2,'confirmed then ready',[confirmed,ready]],[3,'confirmed 2s then ready',[...Array(8).fill(confirmed),ready]],[4,'blank 3s then ready',[confirmed,...Array(12).fill(''),ready]],[5,'blank 6s then ready',[confirmed,...Array(24).fill(''),ready]],[6,'metadata during blank then ready',[confirmed,'','',ready]]])test(`${String(n).padStart(2,'0')} trust ${name}`,async()=>assert.equal((await accept(sim(frames))).state,'READY'));
test('07 trust Enter only once',async()=>{const c=sim([confirmed,'',ready]);await accept(c);assert.equal(c.inputs,1)});
test('08 confirmed trust never sends second Enter',async()=>{const c=sim([confirmed,confirmed,confirmed,ready]);await accept(c);assert.equal(c.inputs,1)});
test('09 blank redraw is transitional',()=>assert.equal(classifyStartupScreen('').kind,'BLANK_REDRAW'));
test('10 stable blank is not interactive',()=>assert.equal(classifyStartupScreen('   ').interactive,undefined));
test('11 single unknown then READY',async()=>assert.equal((await accept(sim(['partial paint',ready]))).state,'READY'));
test('12 two unknown then READY',async()=>assert.equal((await accept(sim(['partial paint','partial paint',ready]))).state,'READY'));
test('13 stable interactive unknown fails',async()=>reject(accept(sim(['Mystery\n1. Continue\nEnter to select'],{deadline:2000})),'UNEXPECTED_POST_TRUST_GATE'));
for(const [n,label,screen] of [[14,'OAuth','OAuth authorization'],[15,'login','Log in to continue'],[16,'theme','Choose a theme'],[17,'permission mode','Select permission mode'],[18,'permission escalation','Permission escalation required']])test(`${n} ${label} fails closed`,async()=>reject(accept(sim([screen])),'UNEXPECTED_POST_TRUST_GATE'));
test('19 wrong workspace fails closed',async()=>reject(acceptWorkspaceTrustGate({context:ctx({displayedWorkspace:'/tmp'}),controller:sim([ready])}),'MANAGED_TRUST_CONTEXT_REJECTED'));
test('20 process exit during blank',async()=>reject(accept(sim([''],{runtime:{processAlive:false}})),'FAILED_PROCESS_EXIT'));
test('21 exact session mismatch',async()=>reject(accept(sim([''],{runtime:{exactSession:false}})),'FAILED_SESSION_MISMATCH'));
test('22 unexpected Claude owner',async()=>reject(accept(sim([''],{runtime:{unexpectedClaudeOwner:true}})),'FAILED_OWNERSHIP_MISMATCH'));
test('23 ownership loss',async()=>reject(accept(sim([''],{runtime:{ownershipIntact:false}})),'FAILED_OWNERSHIP_MISMATCH'));
test('24 startup timeout',async()=>reject(accept(sim([''],{deadline:750})),'FAILED_STARTUP_TIMEOUT'));
test('25 timeout sends no extra input',async()=>{const c=sim([''],{deadline:500});await assert.rejects(accept(c));assert.equal(c.inputs,1)});
test('26 zero conversational records allowed',async()=>assert.equal((await accept(sim([ready]))).state,'READY'));
test('27 unexpected user record fails',async()=>reject(accept(sim([''],{transcript:{user:1}})),'UNEXPECTED_USER_RECORD'));
test('28 unexpected assistant fails',async()=>reject(accept(sim([''],{transcript:{assistant:1}})),'UNEXPECTED_ASSISTANT_RECORD'));
test('29 compact fails',async()=>reject(accept(sim([''],{transcript:{compact:true}})),'UNEXPECTED_COMPACT'));
test('30 startup metadata allowed',async()=>assert.equal((await accept(sim(['',ready],{transcript:{metadata:['atis-latch'],user:0,assistant:0}}))).state,'READY'));
test('31 READY checked before unknown',async()=>assert.equal(classifyStartupScreen(ready).kind,'READY'));
test('32 READY needs no byte stability',async()=>assert.equal((await accept(sim([ready+' spinner']))).state,'READY'));
test('33 blank stable over 500ms allowed',async()=>assert.equal((await accept(sim(['','','',ready]))).state,'READY'));
test('34 blank stable over 5s allowed',async()=>assert.equal((await accept(sim([...Array(21).fill(''),ready]))).state,'READY'));
test('35 deadline finite',()=>assert.equal(POST_TRUST_DEADLINE_MS,30000));
test('36 cleanup possible after timeout',async()=>{let cleaned=false;try{await accept(sim([''],{deadline:1}))}catch{}finally{cleaned=true}assert(cleaned)});
test('37 cleanup possible after gate',async()=>{let cleaned=false;try{await accept(sim(['OAuth']))}catch{}finally{cleaned=true}assert(cleaned)});
test('38 rollback compatibility preserved',async()=>{let rollback=false;try{await accept(sim([''],{runtime:{processAlive:false}}))}catch{rollback=true}assert(rollback)});
test('39 strict MCP isolation preserved',()=>assert(shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'}).args.includes('--strict-mcp-config')));
test('40 production helper ownership preserved',async()=>assert.equal((await accept(sim([ready],{runtime:{unexpectedHelperOwner:false}}))).state,'READY'));
test('41 trust validator unchanged',()=>assert.equal(validateManagedTrustContext(ctx()),true));
test('42 wrong operation target rejected',()=>assert.throws(()=>validateManagedTrustContext(ctx({targetSessionId:crypto.randomUUID()}))));
test('43 wrong UID rejected',()=>assert.throws(()=>validateManagedTrustContext(ctx({uid:1}))));
test('44 wrong HOME rejected',()=>assert.throws(()=>validateManagedTrustContext(ctx({home:'/tmp'}))));
test('45 wrong cwd rejected',()=>assert.throws(()=>validateManagedTrustContext(ctx({canonicalCwd:'/tmp'}))));
test('46 dangerous permissions absent',()=>assert(!shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'}).args.includes('--dangerously-skip-permissions')));
test('47 permission mode unchanged',()=>assert(!shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'}).args.includes('--permission-mode')));
test('48 deny list fingerprint preserved',async()=>{const c=sim([ready]);assert.equal(await c.permissionFingerprint(),'p');await accept(c)});
test('49 hooks fingerprint preserved',async()=>{const c=sim([ready]);await accept(c);assert.equal(await c.permissionFingerprint(),'p')});
test('50 version probe must precede owner snapshot',async()=>{const order=[];await Promise.resolve().then(()=>order.push('version-complete'));order.push('owner-snapshot');assert.deepEqual(order,['version-complete','owner-snapshot'])});
test('51 poll interval is bounded',()=>assert.equal(POST_TRUST_POLL_MS,250));
