import test from 'node:test';import assert from 'node:assert/strict';
import {acceptWorkspaceTrustGate,assertSafeClaudeArgs,detectWorkspaceTrustGate,handleManagedStartup,readWorkspaceTrustDiagnostic,validateManagedTrustContext} from '../deploy/rsc-startup-trust.mjs';
import {handleShadowStartup,launchShadowWithTrust,shadowLaunchSpec,verifyWorkspaceTrust} from '../src/runtimes/rsc/shadow.mjs';
const id='22222222-2222-4222-8222-222222222222';
const trust=(ws='/root')=>`Accessing workspace:\n\n ${ws}\n\n Quick safety check: Is this a project you created or one you trust?\n Claude Code'll be able to read, edit, and execute files here.\n ❯ 1. Yes, I trust this folder\n   2. No, exit`;
const ready='Claude Code v2.1.236\n/root\n❯ Try "hello"';
const context=(over={})=>({executable:'/usr/bin/claude',version:'2.1.236',managedOperation:true,targetSessionId:id,expectedTargetSessionId:id,uid:0,home:'/root',canonicalCwd:'/root',displayedWorkspace:'/root',unexpectedClaudeOwner:false,unexpectedHelperOwner:false,...over});
const controller=(over={})=>{let screen=over.initial??trust(),confirms=0,time=0;return {screen:async()=>screen,conversationCounts:async()=>({user:0,assistant:0}),permissionFingerprint:async()=>'same',confirmSelectedOption:async()=>{confirms++;screen=over.after??ready},runtimeEvidence:async()=>({processAlive:over.alive??true,exactSession:true,ownershipIntact:true,unexpectedClaudeOwner:false,unexpectedHelperOwner:false,uid:0,home:'/root',canonicalCwd:'/root'}),transcriptEvidence:async()=>({parseable:true,transcriptWritable:true,resumeHistoryInitialized:true,resumeMetadataInitialized:true,modeObserved:true,permissionModeObserved:true,resumeMilestone:true,startupStructureValid:true,wrongSessionRecord:false,orphanStartupRecord:false,user:0,assistant:0,compact:false}),readyEvidence:async()=>true,mcpCallCount:async()=>over.mcp??0,timing:{pollMs:250,deadlineMs:1500,now:()=>time,sleep:async ms=>{time+=ms}},get confirms(){return confirms},...over};};
const reject=async(fn,reason)=>assert.rejects(fn,e=>e.reason===reason);
test('01 direct READY has no trust interaction',async()=>{const c=controller({initial:ready});assert.equal((await handleManagedStartup({context:context(),controller:c})).interactionCount,0);assert.equal(c.confirms,0)});
test('02 exact root trust is accepted',async()=>assert.equal((await handleManagedStartup({context:context(),controller:controller()})).accepted,true));
test('03 displayed /root slash canonical identity is accepted',()=>assert.equal(detectWorkspaceTrustGate(trust('/root/')).workspace,'/root'));
test('04 workspace /tmp rejected',async()=>reject(()=>handleManagedStartup({context:context(),controller:controller({initial:trust('/tmp')})}),'MANAGED_TRUST_CONTEXT_REJECTED'));
test('05 workspace /home/foo rejected',async()=>reject(()=>handleManagedStartup({context:context(),controller:controller({initial:trust('/home/foo')})}),'MANAGED_TRUST_CONTEXT_REJECTED'));
for(const [n,label,screen] of [[6,'OAuth','OAuth required'],[7,'login','Log in to continue'],[8,'browser auth','Opening browser to sign in'],[9,'theme','Choose a theme'],[10,'permission','Permission prompt: allow this tool'],[11,'unknown numbered','1. Continue\n2. Exit'],[12,'ambiguous','Accessing workspace: /root\nYes, trust']])test(`${String(n).padStart(2,'0')} ${label} prompt rejected`,async()=>reject(()=>handleManagedStartup({context:context(),controller:controller({initial:screen})}),'UNEXPECTED_INTERACTIVE_GATE'));
test('13 wrong Claude version rejected',()=>assert.throws(()=>validateManagedTrustContext(context({version:'2.1.237'})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('14 wrong UID rejected',()=>assert.throws(()=>validateManagedTrustContext(context({uid:1000})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('15 wrong HOME rejected',()=>assert.throws(()=>validateManagedTrustContext(context({home:'/tmp'})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('16 wrong cwd rejected',()=>assert.throws(()=>validateManagedTrustContext(context({canonicalCwd:'/tmp'})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('17 unmanaged operation rejected',()=>assert.throws(()=>validateManagedTrustContext(context({managedOperation:false})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('18 wrong target ownership rejected',()=>assert.throws(()=>validateManagedTrustContext(context({targetSessionId:crypto.randomUUID()})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('19 acceptance emits no user record',async()=>{let calls=0;const c=controller({conversationCounts:async()=>{calls++;return {user:0,assistant:0}}});await acceptWorkspaceTrustGate({context:context(),controller:c});assert.equal(calls,1)});
test('20 acceptance emits no assistant turn',async()=>{const c=controller();await acceptWorkspaceTrustGate({context:context(),controller:c})});
test('21 acceptance calls no MCP',async()=>{const c=controller();await acceptWorkspaceTrustGate({context:context(),controller:c});assert.equal(await c.mcpCallCount(),0)});
test('22 acceptance preserves permission fingerprint',async()=>{const c=controller();await acceptWorkspaceTrustGate({context:context(),controller:c});assert.equal(await c.permissionFingerprint(),'same')});
test('23 dangerous permission bypass is rejected',()=>assert.throws(()=>assertSafeClaudeArgs(['--strict-mcp-config','--dangerously-skip-permissions']),/PERMISSION_BOUNDARY_CHANGED/));
for(const [n,value,label] of [[24,false,'false'],[25,true,'true']])test(`${n} persisted trust ${label} permits startup`,async()=>{const r=await verifyWorkspaceTrust({readFileFn:async()=>JSON.stringify({projects:{'/root':{hasTrustDialogAccepted:value}}}),realpathFn:async()=>'/root'});assert.equal(r.shadowPreflightAllowed,true);assert.equal(r.workspaceTrustPersisted,value)});
test('26 missing trust field permits exact managed startup',async()=>assert.equal((await readWorkspaceTrustDiagnostic({readFileFn:async()=>JSON.stringify({projects:{'/root':{}}})})).persisted,false));
test('27 malformed state never authorizes persistence',async()=>assert.deepEqual(await readWorkspaceTrustDiagnostic({readFileFn:async()=>'{'}),{readable:false,persisted:false,value:undefined}));
test('28 persistent redraw is safe after durable resume',async()=>assert.equal((await acceptWorkspaceTrustGate({context:context(),controller:controller({after:''})})).state,'READY'));
test('29 target exit during trust fails closed',async()=>reject(()=>acceptWorkspaceTrustGate({context:context(),controller:controller({alive:false})}),'FAILED_PROCESS_EXIT'));
test('30 readiness failure after trust fails closed',async()=>reject(()=>acceptWorkspaceTrustGate({context:context(),controller:controller({after:'Permission prompt: approve tool'})}),'UNEXPECTED_POST_TRUST_GATE'));
test('31 trust errors remain catchable by rollback',async()=>{let rollback=false;try{await acceptWorkspaceTrustGate({context:context(),controller:controller({alive:false})})}catch{rollback=true}assert.equal(rollback,true)});
test('32 gate can reopen after rollback',()=>{let gate='CLOSED';gate='OPEN';assert.equal(gate,'OPEN')});
test('33 no duplicate trust input',async()=>{const c=controller();await acceptWorkspaceTrustGate({context:context(),controller:c});assert.equal(c.confirms,1)});
test('34 exact option selected once',async()=>{const c=controller();const r=await acceptWorkspaceTrustGate({context:context(),controller:c});assert.equal(r.interactionCount,1)});
test('35 second onboarding after trust fails closed',async()=>reject(()=>acceptWorkspaceTrustGate({context:context(),controller:controller({after:'Choose a theme'})}),'UNEXPECTED_POST_TRUST_GATE'));
test('36 production source is absent from handler inputs',()=>assert.doesNotMatch(JSON.stringify(context()),/6ab4267b/));
test('37 production helper is absent from handler inputs',()=>assert.doesNotMatch(JSON.stringify(context()),/qiuqiu-frontend-message/));
test('38 strict MCP isolation is preserved',()=>assertSafeClaudeArgs(shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'}).args));
test('39 target session is exact',()=>assert.equal(shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'}).args[1],id));
test('40 handler cannot request compact',()=>assert.doesNotMatch(JSON.stringify(shadowLaunchSpec({targetSessionId:id,settingsPath:'s',mcpConfigPath:'m'})),/compact/i));
test('41 wrong Claude owner rejected',()=>assert.throws(()=>validateManagedTrustContext(context({unexpectedClaudeOwner:true})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('42 wrong helper owner rejected',()=>assert.throws(()=>validateManagedTrustContext(context({unexpectedHelperOwner:true})),/MANAGED_TRUST_CONTEXT_REJECTED/));
test('43 permission-mode changes are rejected',()=>assert.throws(()=>assertSafeClaudeArgs(['--strict-mcp-config','--permission-mode','auto']),/PERMISSION_BOUNDARY_CHANGED/));
test('44 shadow uses shared startup handler',async()=>assert.equal((await handleShadowStartup({context:context(),controller:controller({initial:ready})})).state,'READY'));
test('45 malformed diagnostic state never blocks launch',async()=>{let started=false;await launchShadowWithTrust({readFileFn:async()=>'{bad',realpathFn:async()=>'/root',start:async()=>{started=true}});assert.equal(started,true)});
