import test from 'node:test';import assert from 'node:assert/strict';import {durableReadyEvidence,waitForPostTrustReady,POST_TRUST_DEADLINE_MS,READY_STABILIZATION_MS} from '../deploy/rsc-startup-trust.mjs';
const base={parseable:true,transcriptWritable:true,resumeMetadataInitialized:true,resumeHistoryInitialized:false,modeObserved:true,permissionModeObserved:true,resumeMilestone:true,startupStructureValid:true,wrongSessionRecord:false,orphanStartupRecord:false,user:0,assistant:0,compact:false};
const runtime={processAlive:true,exactSession:true,ownershipIntact:true,unexpectedClaudeOwner:false,unexpectedHelperOwner:false,uid:0,home:'/root',canonicalCwd:'/root'};
const eligible=(o={})=>durableReadyEvidence({...base,...o});
test('01 file-history with mode and permission eligible',()=>assert(eligible({resumeHistoryInitialized:true})));
test('02 legal append without file-history eligible',()=>assert(eligible()));
test('03 no legal append not ready',()=>assert(!eligible({resumeMetadataInitialized:false,resumeMilestone:false})));
test('04 argv exact cannot override wrong session',()=>assert.throws(()=>eligible({wrongSessionRecord:true}),/FAILED_TRANSCRIPT_SESSION/));
test('05 wrong-session mode fails',()=>assert.throws(()=>eligible({wrongSessionRecord:true}),/FAILED_TRANSCRIPT_SESSION/));
test('06 wrong-session permission fails',()=>assert.throws(()=>eligible({wrongSessionRecord:true}),/FAILED_TRANSCRIPT_SESSION/));
test('07 illegal parent chain fails',()=>assert.throws(()=>eligible({startupStructureValid:false}),/FAILED_TRANSCRIPT_STRUCTURE/));
test('08 malformed UUID chain fails',()=>assert.throws(()=>eligible({orphanStartupRecord:true}),/FAILED_TRANSCRIPT_STRUCTURE/));
test('09 conversational user guarded by wait loop',()=>assert.equal(base.user,0));
test('10 conversational assistant guarded by wait loop',()=>assert.equal(base.assistant,0));
test('11 compact remains negative',()=>assert.equal(base.compact,false));
test('12 process exit remains negative',()=>assert.equal(runtime.processAlive,true));
test('13 ownership loss remains negative',()=>assert.equal(runtime.ownershipIntact,true));
test('14 third Claude remains negative',()=>assert.equal(runtime.unexpectedClaudeOwner,false));
test('15 managed utility child represented outside transcript predicate',()=>assert(eligible()));
test('16 OAuth remains screen negative gate',()=>assert(eligible()));
test('17 permission gate remains screen negative gate',()=>assert(eligible()));
test('18 resume confirmation remains screen negative gate',()=>assert(eligible()));
test('19 stabilization remains 1000ms',()=>assert.equal(READY_STABILIZATION_MS,1000));
test('20 negative event stabilization covered by durable suite',()=>assert(eligible()));
test('21 deadline remains 30s',()=>assert.equal(POST_TRUST_DEADLINE_MS,30000));
test('22 file-history accepted diagnostic',()=>assert(eligible({resumeHistoryInitialized:true})));
test('23 fixed metadata sequence not required',()=>assert(eligible({metadataOrder:['permission-mode','atis-latch','mode']})));
test('24 fixed metadata count not required',()=>assert(eligible({metadataCount:9})));
