const FRONTEND_DELIVERY='mcp__qiuqiu-frontend__send_frontend_message';
const secret=/(authorization|bearer|api[_ -]?key|oauth|token|cookie|secret|password)/i;
const absolutePath=/(?:^|\s)(?:[A-Za-z]:\\|\/(?:root|home|etc|opt|var|tmp)\/)[^\s]*/g;
const base64=/\b[A-Za-z0-9+/]{120,}={0,2}\b/g;
export function sanitizeThoughtText(value,{max=1200}={}){let text=String(value??'').replace(base64,'[hidden data]').replace(absolutePath,'[hidden path]');if(secret.test(text))return '[sensitive details hidden]';return text.slice(0,max)}
const displayName=name=>({Read:'读取',Write:'写入',Edit:'编辑',Bash:'运行命令',WebSearch:'搜索',WebFetch:'读取网页',ToolSearch:'查找工具','mcp__qiuqiu-frontend__read_frontend_image':'读取照片','mcp__qiuqiu-frontend__read_time_anchor':'读取时间信息'}[name]||String(name||'工具').split('__').at(-1).replaceAll('_',' '));
function inputSummary(input){if(!input||typeof input!=='object')return '';for(const key of ['query','q','name','albumId','photoId'])if(typeof input[key]==='string')return sanitizeThoughtText(`${key}: ${input[key]}`,{max:240});return ''}
const isFrontendDeliveryDiscovery=block=>block?.type==='tool_use'&&block.name==='ToolSearch'&&block.input?.query===`select:${FRONTEND_DELIVERY}`;
export function normalizeThoughtRecords(records){const items=[];for(const record of records){const blocks=Array.isArray(record?.message?.content)?record.message.content:[];for(let index=0;index<blocks.length;index++){const block=blocks[index],id=`${record.uuid||record.timestamp||'record'}:${index}`;if(block?.type==='thinking'&&typeof block.thinking==='string'&&block.thinking.trim())items.push({id,type:'thinking',text:sanitizeThoughtText(block.thinking),timestamp:record.timestamp||null,order:items.length});if(block?.type==='tool_use'&&block.name!==FRONTEND_DELIVERY&&!isFrontendDeliveryDiscovery(block))items.push({id,type:'tool_call',toolName:String(block.name||'').slice(0,160),displayName:displayName(block.name).slice(0,120),inputSummary:inputSummary(block.input),status:'running',timestamp:record.timestamp||null,order:items.length,toolUseId:String(block.id||'')});if(block?.type==='tool_result'){const match=[...items].reverse().find(item=>item.type==='tool_call'&&item.toolUseId===block.tool_use_id);if(match)match.status=block.is_error?'failed':'completed'}}}return {items:items.slice(-40).map(({toolUseId,...item},order)=>({...item,order})),suppressOrdinaryBody:false}}
export {FRONTEND_DELIVERY};
