import {mkdir,open,readFile,rename,rm,chmod} from 'node:fs/promises';import {dirname,join} from 'node:path';
const QUEUE_STATES=new Set(['ACTIVATING','STARTING_TARGET','TARGET_READY','COMMITTING','RECOVER_LAST_GOOD']);
const id=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function validateProductionRscState(value){if(!value||!id.test(value.currentProductionSessionId||'')||!id.test(value.lastGoodSessionId||'')||!id.test(value.preparedTargetSessionId||'')||!['VALIDATED','CANDIDATE_ACTIVE','ACTIVE','FAILED_SAFE',...QUEUE_STATES].includes(value.handoffState)||!Number.isSafeInteger(value.handoffGeneration)||value.handoffGeneration<1)throw new Error('INVALID_RSC_PRODUCTION_STATE');return value}
export function shouldQueueRscSend(state){return QUEUE_STATES.has(state.handoffState)}
export function createProductionRscStateStore({path}){let current;return {path,async load(){current=validateProductionRscState(JSON.parse(await readFile(path,'utf8')));return current},get(){return current},async save(value){validateProductionRscState(value);await mkdir(dirname(path),{recursive:true,mode:0o700});const temp=join(dirname(path),`.rsc-${process.pid}-${Date.now()}.tmp`),h=await open(temp,'wx',0o600);try{await h.writeFile(JSON.stringify(value,null,2)+'\n');await h.sync();await h.close();await rename(temp,path);await chmod(path,0o600);if(process.platform!=='win32'){const d=await open(dirname(path),'r');await d.sync();await d.close()}current=value;return value}catch(e){await h.close().catch(()=>{});await rm(temp,{force:true});throw e}}}}
export function createProductionRscCoordinator({stateStore,maxQueued=16,maxWaitMs=120000,pollMs=250,setTimer=setTimeout,clearTimer=clearTimeout,now=()=>Date.now()}){
 const queue=new Map();let pollTimer=null;const clearItemTimer=item=>{if(item.timer!=null){clearTimer(item.timer);item.timer=null}},terminate=(item,key)=>{if(item.terminal)return false;item.terminal=true;queue.delete(key);clearItemTimer(item);return true};
 const release=async()=>{const items=[...queue.entries()];for(const [key,item] of items){if(!terminate(item,key))continue;try{item.resolve(await item.run())}catch(e){item.reject(e)}}return items.filter(([,item])=>item.terminal).length};
 const poll=async()=>{pollTimer=null;if(!queue.size)return;try{if(!shouldQueueRscSend(await stateStore.load()))return void await release()}catch{}pollTimer=setTimer(poll,pollMs)};
 return {async submit(request,run){const state=await stateStore.load();if(state.handoffState==='CANDIDATE_ACTIVE'){const result=await run(),latest=await stateStore.load();if(latest.handoffState==='CANDIDATE_ACTIVE')await stateStore.save({...latest,currentProductionSessionId:latest.preparedTargetSessionId,lastGoodSessionId:latest.preparedTargetSessionId,handoffState:'ACTIVE',updatedAt:new Date(now()).toISOString()});return result}if(!shouldQueueRscSend(state))return run();const key=request.clientRequestId;if(!key)throw Object.assign(new Error('clientRequestId required during handoff'),{statusCode:400});if(queue.has(key))return queue.get(key).promise;if(queue.size>=maxQueued)throw Object.assign(new Error('rsc_send_queue_full'),{statusCode:503});let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b}),item={request:{...request,imageIds:[...(request.imageIds||[])]},run,resolve,reject,promise,queuedAt:now(),timer:null,terminal:false};item.timer=setTimer(()=>{if(!terminate(item,key))return;item.reject(Object.assign(new Error('rsc_send_queue_timeout'),{statusCode:503}))},maxWaitMs);queue.set(key,item);if(!pollTimer)pollTimer=setTimer(poll,pollMs);return promise},releaseToAuthoritative:release,size(){return queue.size},state:()=>stateStore.get(),async snapshot(){const state=await stateStore.load(),items=[...queue.values()],oldest=items.length?Math.min(...items.map(item=>item.queuedAt)):null;return {state:shouldQueueRscSend(state)?'CLOSED':'OPEN',queueDepth:items.length,oldestQueuedMs:oldest===null?null:Math.max(0,now()-oldest),generation:state.handoffGeneration,handoffGeneration:state.handoffGeneration,handoffState:state.handoffState}}}
}
